# Generated by Django 3.2 on 2021-04-27 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "name",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("coingecko_id", models.CharField(max_length=32)),
                ("last_update", models.DateField()),
                ("fiat", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "name",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("provider", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Value",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.FloatField()),
                (
                    "coin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crypto.coin"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_executed", models.DateField()),
                (
                    "typ",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("order", "Order"),
                            ("withdraw", "Withdraw"),
                        ],
                        max_length=16,
                    ),
                ),
                ("bought_quantity", models.FloatField(null=True)),
                ("sold_quantity", models.FloatField(null=True)),
                ("fee_quantity", models.FloatField(null=True)),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("add_funds", "Add funds"),
                            ("gift_received", "Gift received"),
                            ("ignored", "Ignored"),
                            ("income", "Income"),
                            ("internal", "Internal"),
                            ("mined", "Mined"),
                            ("remove_funds", "Remove funds"),
                            ("staked", "Staked"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "bought_currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bought",
                        to="crypto.coin",
                    ),
                ),
                (
                    "fee_currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="fee",
                        to="crypto.coin",
                    ),
                ),
                (
                    "sold_currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="sold",
                        to="crypto.coin",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="crypto.wallet"
                    ),
                ),
            ],
        ),
    ]
