# Generated by Django 3.2 on 2021-04-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0002_alter_coin_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin", name="last_update", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="log", name="time_executed", field=models.DateTimeField(),
        ),
    ]
