# Generated by Django 3.2 on 2021-04-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0003_auto_20210427_1656"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="value",
            index=models.Index(
                fields=["coin", "-date"], name="crypto_valu_coin_id_2abfdb_idx"
            ),
        ),
    ]
