# Generated by Django 3.2 on 2021-04-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0006_remove_value_crypto_valu_coin_id_204479_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="value",
            index=models.Index(
                fields=["coin", "-date"], name="crypto_valu_coin_id_2abfdb_idx"
            ),
        ),
    ]
