# Generated by Django 3.2 on 2021-04-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0007_value_crypto_valu_coin_id_2abfdb_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="log",
            index=models.Index(
                fields=["time_executed", "typ"], name="crypto_log_time_ex_5ea5a8_idx"
            ),
        ),
    ]
