# Generated by Django 3.2.5 on 2021-11-01 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0013_cryptocomdeposit_cryptocominterest_cryptocomwithdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptocomStakeInterest',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crypto.log')),
            ],
            bases=('crypto.log',),
        ),
        migrations.CreateModel(
            name='CryptocomSupercharger',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crypto.log')),
            ],
            bases=('crypto.log',),
        ),
        migrations.CreateModel(
            name='CryptocomTradeFeeRebate',
            fields=[
                ('log_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crypto.log')),
            ],
            bases=('crypto.log',),
        ),
        migrations.DeleteModel(
            name='CryptocomInterest',
        ),
    ]
